### ISSUE TITLE
Cannot import "ServiceSensor" project

### ISSUE THREAD

**Issue by Schabolon** [seemoo-lab/seemoo-wearable-sensing#1]
Hi,

I tried to import the native projekt (ServiceSensor) according to the readme (Import native and web projects by using `File -> Import -> Tizen -> Tizen Project` and following the wizzard instructions.) But this way, just the HelloAccessoryProvider-project can be importet. I tried importing the project by clicking on `File -> Import -> Existing Projects` into Workspace but in this case, I can't run the project! Whenever I click on `Run As`, I just have the option to Run Configurations and I can't run the project.

Tizen-version (of my watch):  4.0.0.2
Tizen-studio version: 3.1

Hopefully, you can help me :)
Schabolon

**Comment by fommike** [comment]
Jakob Hey,

Indeed, there was a problem with importing the native-app as one of the project files got lost somehow;) I have added it now and run the app on my watch one more time—everything seems to be working. 

Check if the import and compilation work for you (just follow the Readme), then I will close this issue. 

Best,

Mikhail

**Comment by Schabolon** [comment]
Hi Mikhail,

Thank you for your fast response 👍 
I pulled the changes and now it is working, so the issue can be closed.

Best regards,
Jakob
