### ISSUE TITLE
Battery life estimation with app running

### ISSUE THREAD

**Issue by filby89** [seemoo-lab/seemoo-wearable-sensing#2]
Thank you very much for open sourcing your application. Have you done any measurements regarding the battery life of the watch when the service is continuously running ?

**Comment by fommike** [comment]
Panagiotis Hey,

Glad you found the app useful;) As a matter of fact we did measure battery's lifetime—with all sensors running (our default sampling rates) the app should last 8-9 hours (tested on a Gear S3). Though, I do not know "contributions" of each individual sensors.

Hope that helps.

Best,

Mikhail

**Comment by filby89** [comment]
Thank you very much for your reply. I am currently doing experiments to check battery life too. 
Also, is there a specific reason why you are not using the timestamp included in the sensor_event_s struct but use clock_gettime ?

**Comment by fommike** [comment]
Hey,

We used _clock_gettime_ to get a millisecond accuracy for timestamps (to comply with our evaluation scripts). Can you share some of your results for the battery lifetime (I wonder if you get similar results to ours)? 

If you don't have further questions about the battery lifetime—the issue can be close.

**Comment by filby89** [comment]
Hello !
In our case we were only interested in the accelerometer and gyro data at 20 hz. We found out that the battery life in this case can last 24+ hours !
