### ISSUE TITLE
Sending gear s3 data to smartphone

### ISSUE THREAD

**Issue by alterreal** [seemoo-lab/seemoo-wearable-sensing#3]
Hey! Thank you for sharing your code, it is being quite useful to me. I want to record green LED and IMU data from the gear s3. Although the green LED data was not included in your code i managed to add it and it is working fine. 

I saw in your web app js code that there are some functions created for sending the streamed data to the smartphone. However i'm not really sure if they are used at all. I was interested in sending the data to my smartphone, is it possible to do so with your app?

Cheers,
Alex

**Comment by fommike** [comment]
Hey Alex,

I am glad to hear that you found the app useful! I am pretty sure that there is a possibility to stream the data from the S3 to the phone, however, we did not do it. So we might have implemented some functionality there but I cannot say how reliable this would work.

On the same note: we stored the collected sensor data from the S3 on the watch itself for a reason. I have a bit of experience with different sensing platforms. and if the reliability of data collection is of importance to you than I suggest going with that option. For example, we found the S3 (at least with the OS version we tested it) to be very good at keeping the set sampling rate (e.g., 50 Hz), when collecting the sensor data. If you stream the data over Bluetooth than you will inevitably loss some packets, may experience disconnects between the watch and phone, etc.—these factors would be even more prominent if you wear the watch, i.e., the user mobility is involved. 

So overall, the streaming of the sensor data is possible, but you would need to see if the functionality that we implemented actually does that. If you manage to extend the app with this feature + test it, in addition to, the LED data capture—you may consider opening a pull request. 

I hope that helps. I have enabled the discussions option for this project to ask questions like there. With that I am closing this issue. 

Best,

Mikhail

**Comment by alterreal** [comment]
Thanks for the reply, Mikhail.

I appreciate your advice. I made this question because i would like to acquire data with both smartwatch and smartphone, the communication between both would be mainly for purposes of synchronizing data or making it more easy to process afterwards. But then again, the reliability of data collection is key for the target application. In any case, if i venture to try to send the data to the smartphone i'll sure to share it.

Kind regards,
Alex
